Nasbench201
Multi-Objective-NAS/nasbench pull request #1
Opened 2020-08-08 16:15 UTC by young917

SemiNAS 에서 필요하면서 nasbench 201 과 통일된 함수로 호출할 수 있게 api에 함수를 추가했습니다.

예시는 nasbench 201 How to use.ipynb를 보는 게 좋을 것 같습니다!

인덴트가 tab에서 space로 바꾸는 과정이 들어가서 보기 복잡할 것 같습니다ㅠㅠㅠ

2020-08-23 09:45 UTC, juice500ml requested changes
Please fix this branch to rebase after the reindentation. It is basically impossible to review much further.
Also, you should make `self-supervised-nas` branch, and merge to that branch, not the `master` branch!

2020-08-23 09:45 UTC, juice500ml commented on NASBench.ipynb
>  {
Why is there edits for this file? I can't see why.

2020-08-23 09:45 UTC, juice500ml commented on nasbench/lib/model_spec.py
> +    def __init__(self, matrix, ops, data_format='channels_last'):
Exact same `ModelSpec` object seems to be used in `nasbench201` as well. Please remove duplicate code, and use `nasbench.ModelSpec` class directly in` `nasbench201`.

2020-08-23 09:47 UTC, juice500ml commented
Please consider using IDEs like vscode. If you have trouble preparing development environment, feel free to tell me any time. Also, I'm very skeptical on changing the indentation of the original code base, as this will raise numerous merge conflicts when the `master` branch gets updated. Please consider reverting the changes, and follow the google's indentation again.

2020-08-24 15:09 UTC, juice500ml requested changes

2020-08-24 15:09 UTC, juice500ml commented on nasbench/api.py
> +  def get_model_spec_by_hash(self, hash):
`hash` is a builtin function. Please avoid using the name `hash`.

2020-08-24 15:09 UTC, juice500ml commented on nasbench/api.py
> +  def get_modelspec(self, matrix, ops):
Why is there two `get_modelspec`?

2020-08-24 15:09 UTC, juice500ml commented on nasbench/lib/model_spec.py
> +    self.search_space = ['input', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'maxpool3x3', 'output']
Why is there two `search_space`?

2020-08-30 00:14 UTC, young917 commented on nasbench/api.py
> +  def get_model_spec_by_hash(self, hash):
네!

2020-08-30 00:14 UTC, young917 commented on nasbench/api.py
> +  def get_modelspec(self, matrix, ops):
하나는 없앴습니다!

2020-08-30 00:36 UTC, young917 commented on nasbench/lib/model_spec.py
> +    def __init__(self, matrix, ops, data_format='channels_last'):
https://github.com/Multi-Objective-NAS/NAS-Bench-201/blob/nasbench201/nas_201_api/model_spec.py
```model_spec_201.py``` -> ```model_spec.py``` 로 변경하여 101과 201에서 모두 사용할 수 있게 바꾸었다고 생각합니다...!

2020-08-30 00:39 UTC, young917 commented on nasbench/lib/model_spec.py
> +    def __init__(self, matrix, ops, data_format='channels_last'):
https://github.com/Multi-Objective-NAS/NAS-Bench-201/blob/f8118f2e7953ed7a1d2615762cd0f3994db84ffe/nas_201_api/api_201.py#L19

https://github.com/Multi-Objective-NAS/nasbench/blob/b94247037ee470418a3e56dcb83814e9be83f3a8/nasbench/api.py#L100

그렇지만 api에서 model spec을 불러오는 것은 현재 101이나 201이 각자의 폴더에 존재하는 model_spec을 각각 불러오는 것으로 되어있습니다..!

2020-08-30 00:44 UTC, young917 commented on nasbench/lib/model_spec.py
> +    self.search_space = ['input', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'maxpool3x3', 'output']
model_spec 에서 search_space는 없앴습니다!

https://github.com/Multi-Objective-NAS/nasbench/blob/b94247037ee470418a3e56dcb83814e9be83f3a8/nasbench/api.py#L389
101 api의 경우, ```self.config['available ops']``` 로 search space가 정의되어 있고


201 api의 경우 ```self.search_space``` 로 정의되어 있습니다.

model spec에서는 필요하지 않다고 생각들어서 search_space를 없앴습니다.
다만, 201 api 의 경우 edge label graph -> node label graph 로 변경하는데 필요해서 method 내 변수로 search space를 정의해서 사용했습니다.

2020-08-30 08:40 UTC, juice500ml commented on nasbench/lib/model_spec.py
> +    def __init__(self, matrix, ops, data_format='channels_last'):
ack

2020-08-30 08:40 UTC, juice500ml commented on nasbench/lib/model_spec.py
> +    self.search_space = ['input', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'maxpool3x3', 'output']
ack

2020-08-30 08:41 UTC, juice500ml reviewed
Feel free to merge if necessary.

2020-09-06 09:21 UTC, merged